---
# Copyright (C) 2020 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later


- name: (openSUSE Leap) Install WireGuard packages
  community.general.zypper:
    name:
      - "wireguard-tools"
    state: present
