---
# Copyright (C) 2021-2025 Tobias Richter
# SPDX-License-Identifier: GPL-3.0-or-later

- name: (Proxmox) Add WireGuard repository
  ansible.builtin.apt_repository:
    repo: "deb http://deb.debian.org/debian buster-backports main"
    state: present
    update_cache: "{{ wireguard_update_cache }}"
  when: ansible_distribution_version | int <= 10

- name: (Proxmox lxc) Install wireguard-tools.
  ansible.builtin.apt:
    install_recommends: false
    name:
      - wireguard-tools
    state: present
