---
# Copyright (C) 2018-2025 Robert Wimmer
# Copyright (C) 2019-2025 Ties de Kock
# SPDX-License-Identifier: GPL-3.0-or-later

- name: (Debian) Install WireGuard packages
  ansible.builtin.apt:
    name:
      - "wireguard"
    state: present
    update_cache: "{{ wireguard_update_cache }}"
