---
- name: (Debian) Install GPG - required to add wireguard key
  apt:
    name: gnupg
    state: present

- name: (Debian) Add WireGuard repository on buster or earlier
  apt_repository:
    repo: "deb http://deb.debian.org/debian buster-backports main"
    state: present
    update_cache: yes
  when: ansible_distribution_version | int <= 10
  tags:
    - wg-install

- name: (Debian) Get architecture
  command: "dpkg --print-architecture"
  register: dpkg_arch
  changed_when: False

- set_fact:
    kernel_header_version: {{ '-cloud-' in ansible_kernel | ternary(ansible_kernel,dpkg_arch.stdout) }}

- name: (Debian) Install kernel headers to compile Wireguard with DKMS
  apt:
    name:
      - "linux-headers-{{ kernel_header_version }}"
    state: present

- name: (Debian) Install wireguard packages
  apt:
    name:
      - "wireguard-dkms"
      - "wireguard-tools"
    state: present
  tags:
    - wg-install
