---
# Copyright (C) 2020 Roman Danko
# SPDX-License-Identifier: GPL-3.0-or-later

- name: (CentOS 8) Install EPEL & ELRepo repository
  yum:
    name:
      - epel-release
      - elrepo-release
    update_cache: true

- name: (CentOS 8) Ensure WireGuard DKMS package is removed
  yum:
    name:
      - "wireguard-dkms"
    state: absent

- name: (CentOS 8) Install WireGuard packages
  yum:
    name:
      - "kmod-wireguard"
      - "wireguard-tools"
    state: present
