---
# Copyright (C) 2020-2025 Ties de Kock
# Copyright (C) 2023-2025 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: (Fedora) Install WireGuard packages
  when:
    - ansible_pkg_mgr != "atomic_container"
  ansible.builtin.dnf:
    name:
      - "wireguard-tools"
    state: present
    update_cache: "{{ wireguard_update_cache }}"
