---
# Copyright (C) 2018-2025 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Restart wireguard
  ansible.builtin.service:
    name: "wg-quick@{{ wireguard_interface }}"
    state: "{{ item }}"
  loop:
    - stopped
    - started
  when:
    - wireguard__restart_interface
    - not ansible_os_family == 'Darwin'
    - wireguard_service_enabled == "yes"
  listen: "reconfigure wireguard"

- name: Syncconf wireguard
  ansible.builtin.shell: |
    set -o errexit
    set -o pipefail
    set -o nounset
    systemctl is-active wg-quick@{{ wireguard_interface | quote }} || systemctl start wg-quick@{{ wireguard_interface | quote }}
    wg syncconf {{ wireguard_interface | quote }} <(wg-quick strip /etc/wireguard/{{ wireguard_interface | quote }}.conf)
    exit 0
  register: wireguard__syncconf_out
  changed_when: false
  failed_when: wireguard__syncconf_out.rc != 0
  args:
    executable: "/bin/bash"
  when:
    - not wireguard__restart_interface
    - not ansible_os_family == 'Darwin'
    - wireguard_service_enabled == "yes"
  listen: "reconfigure wireguard"

- name: Generating Netplan Configuration
  ansible.builtin.command: netplan generate
  listen: reconfigure netplan
  notify: netplan apply config
  changed_when: true
  become: true
  when:
    - wireguard_ubuntu_use_netplan

- name: Applying Netplan Configuration
  ansible.builtin.command: netplan apply
  listen: netplan apply config
  notify: restart systemd-networkd
  changed_when: true
  become: true
  when:
    - wireguard_ubuntu_use_netplan
    - wireguard_interface_restart

- name: Restart systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    state: restarted
  listen: restart systemd-networkd
  become: true
  when:
    - wireguard_ubuntu_use_netplan
    - wireguard_interface_restart
